version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5001:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://bunyakorn:!Zazaza080a@cluster0.gojhn.mongodb.net/KMUTT-DB?retryWrites=true&w=majority&appName=Cluster0
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

volumes:
  mongo_data:
